language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - yarn add -g @angular/cli
script:
- ng lint
- yarn run test-headless
- ng build --prod --base-href https://a-faraz.github.io/ngx-demo/
