language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
  - master
before_script:
  - npm install -g yarn
  - yarn global add @angular/cli
script:
- ng lint
- yarn run test-headless
- yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/ngx-demo
  on:
    branch: master
